### ISSUE TITLE
Add links to vulnerability info to results table

### ISSUE THREAD

**Issue by tjarrettveracode** [relaxnow/veracode-container-security-display#1]
I can't figure out how to do it in Bootstrap, but it would be nice to see a link to the vulnerability advisory in the results table.

**Comment by relaxnow** [comment]
Hi @tjarrettveracode ! Thank you for checking this out! The change is not hard, I created an example of how to do it here: https://github.com/relaxnow/veracode-container-security-display/pull/2 .
That said, I'd like to understand more about how this helps you triage vulnerabilities.
It is my experience that links in these types of overviews draw the eye and the mouse cursor but do nothing to actually help triage vulnerabilities.
The link is available in the detail view you get when you click the row, it also give you the details and more information.
In working with customers to triage vulnerabilities I find the description and other URLs very helpful.

Could you say more about the workflow of using the links to triage vulnerabilities?

**Comment by relaxnow** [comment]
What it would look like:
<img width="1187" alt="Screenshot 2023-07-25 at 21 38 51" src="https://github.com/relaxnow/veracode-container-security-display/assets/524386/4b9da64d-c8e0-4dc2-a3f6-0fa21e51d7c7">
